Create.Reports<-function(obj,dataobj){
	#N report
	N<-obj$stats$N
	Nse<-obj$stats$Nse
	dimnames(N)[[1]]<-dataobj$minAge:dataobj$maxAge
	dimnames(N)[[2]]<-dataobj$years
	FF<-obj$stats$FF
	FFse<-obj$stats$FFse
	dimnames(FF)<-dimnames(N)
	Nrse<-Nse/N
	Frse<-FFse/FF
	list(N=N,FF=FF,Nrse=Nrse,Frse=Frse)
}


CreateSummaryTable<-function(fitobj,dataobj,p=0.95){
	years<-dataobj$years
	ssb<-fitobj$stats$ssb
	totb<-fitobj$stats$totb
	Fbar<-fitobj$stats$FbarW
	R<-fitobj$stats$N[1,]
	TC<-dataobj$caton
	pl<-(1-p)/2
	pu<-1-pl
	ssbl<-ssb+qnorm(pl)*fitobj$stats$ssbse
	ssbu<-ssb+qnorm(pu)*fitobj$stats$ssbse
	totbl<-totb+qnorm(pl)*fitobj$stats$totbse
	totbu<-totb+qnorm(pu)*fitobj$stats$totbse
	Fbarl<-Fbar+qnorm(pl)*fitobj$stats$FbarWse
	Fbaru<-Fbar+qnorm(pu)*fitobj$stats$FbarWse
	Rl<-R+qnorm(pl)*fitobj$stats$Nse[1,]
	Ru<-R+qnorm(pu)*fitobj$stats$Nse[1,]

	print(years)
	print(ssb)
	print(pl);print(pu)
	TC<-c(TC,dataobj$CatchPrediction[1])
	print(TC)
	outtable<-data.frame(
Year=years,
Recruit=R,Recruit2.5=Rl,Recruit97.5=Ru,
TSB=totb,TSB2.5=totbl,TSB97.5=totbu,
SSB=ssb,SSB2.5=ssbl,SSB97.5=ssbu,
Landings=TC,
Fbar=Fbar,Fbar2.5=Fbarl,Fbar97.5=Fbaru
)
outtable
}

#This is for exploratory runs
CreateSummaryTableT<-function(fitobj,dataobj,p=0.95){
	years<-dataobj$years
	ssb<-fitobj$stats$ssb
	totb<-fitobj$stats$totb
	Fbar<-fitobj$stats$FbarW
	R<-fitobj$stats$N[1,]
	TC<-dataobj$caton
	pl<-(1-p)/2
	pu<-1-pl
	ssbl<-ssb+qnorm(pl)*fitobj$stats$ssbse
	ssbu<-ssb+qnorm(pu)*fitobj$stats$ssbse
	totbl<-totb+qnorm(pl)*fitobj$stats$totbse
	totbu<-totb+qnorm(pu)*fitobj$stats$totbse
	Fbarl<-Fbar+qnorm(pl)*fitobj$stats$FbarWse
	Fbaru<-Fbar+qnorm(pu)*fitobj$stats$FbarWse
	Rl<-R+qnorm(pl)*fitobj$stats$Nse[1,]
	Ru<-R+qnorm(pu)*fitobj$stats$Nse[1,]

	Rrse<-fitobj$stats$Nse[1,]/R
	ssbrse<-fitobj$stats$ssbse/ssb
	totbrse<-fitobj$stats$totbse/totb
	Fbarrse<-fitobj$stats$FbarWse/Fbar

	print(years)
	print(ssb)
	print(pl);print(pu)
	TC<-c(TC,dataobj$CatchPrediction[1])
	print(TC)
	outtable<-data.frame(
Year=years,
Recruit=R,Rrse=Rrse,Recruit2.5=Rl,Recruit97.5=Ru,
TSB=totb,TSBrse=totbrse,TSB2.5=totbl,TSB97.5=totbu,
SSB=ssb,SSBrse=ssbrse,SSB2.5=ssbl,SSB97.5=ssbu,
Landings=TC,
Fbar=Fbar,Fbarrse=Fbarrse,Fbar2.5=Fbarl,Fbar97.5=Fbaru
)
outtable
}

CreateShortTermPredictionInput<-function(fobj,dataobj){
	ages<-dataobj$minAge:dataobj$maxAge
	N<-fobj$FC0$N[,fobj$years==max(dataobj$years)]
	M<-fobj$Bpars$M[,fobj$years==max(dataobj$years)]
	pm<-fobj$Bpars$propMat[,fobj$years==max(dataobj$years)]
	ws<-fobj$Bpars$stockMeanWeight[,fobj$years==max(dataobj$years)]
	pm<-fobj$Bpars$propMat[,fobj$years==max(dataobj$years)]
	FF<-fobj$FC0$FF[,fobj$yearsF==max(dataobj$years)]
	wc<-fobj$Bpars$catchMeanWeight[,fobj$years==max(dataobj$years)]
	propM<-0
	propF<-0
	out<-data.frame(age=ages,N=N,M=M,pm=pm,propM=propM,propF=propF,ws=ws,FF=FF,wc=wc)
	print(out)
	N<-fobj$FC0$N[,fobj$years==max(dataobj$years)+1]
	N[2:length(N)]<-NA
	M<-fobj$Bpars$M[,fobj$years==max(dataobj$years)+1]
	pm<-fobj$Bpars$propMat[,fobj$years==max(dataobj$years)+1]
	ws<-fobj$Bpars$stockMeanWeight[,fobj$years==max(dataobj$years)+1]
	pm<-fobj$Bpars$propMat[,fobj$years==max(dataobj$years)+1]
	FF<-fobj$FC0$FF[,fobj$yearsF==max(dataobj$years)+1]
	FF<-FF/max(FF)
	wc<-fobj$Bpars$catchMeanWeight[,fobj$years==max(dataobj$years)+1]
	out2<-data.frame(age=ages,N=N,M=M,pm=pm,propM=propM,propF=propF,ws=ws,SF=FF,wc=wc)
	print(out2)
	list(out1=out,out2=out2)
}
